### ISSUE TITLE
Special Character

### ISSUE THREAD

**Issue by DEllement** [fantasydata/fantasydata-api-csharp#2]
Hi, this is Dany from TradeFan, i noticed a problem while fetching the soccer player for FIFA,
some player with special character was not fetched with the proper encoding

so i had to pull the source code and add this line to BaseClient.cs

**client.Encoding = new UTF8Encoding();**

Thanks

**Comment by neipo13** [comment]
Updated in PR #4, will get pushed out to nuget when we push the next version
